// Generated by CoffeeScript 2.3.0
(function () {
  var unorphan;

  unorphan = require('unorphan');

  module.exports = {
    bind: function (el) {
      return unorphan(el);
    }
  };
}).call(this);