// Generated by CoffeeScript 2.3.0
(function () {
  var unorphan;

  unorphan = require('unorphan');

  module.exports = {
    bind: function (el, { value }) {
      if (value !== false) {
        return unorphan(el);
      }
    }
  };
}).call(this);